---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: 192.168.0.21:5000/springcloud/pipeline-base
    tag: 0.7.0
    insecure_registries: [ "192.168.0.21:5000" ]
inputs:
  - name: tools
  - name: repo
  - name: keyval
outputs:
  - name: out
  - name: keyvalout
caches:
  - path: gradle
  - path: maven
run:
  path: tools/concourse/tasks/build-api-compatibility-check/task.sh
