---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: http://192.168.0.21:5000/springcloud/pipeline-base:0.7.0

inputs:
  - name: version
  - name: tools

outputs:
  - name: updated-version
  - name: keyvalout

run:
  path: tools/concourse/tasks/generate-version/task.sh

params:
  GIT_EMAIL:
  GIT_NAME:
