---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: localhost:5000/springcloud/pipeline-base
    tag: "0.7.0"
    insecure_registries: [ "localhost:5000" ]
inputs:
  - name: version
  - name: tools

outputs:
  - name: updated-version
  - name: keyvalout

run:
  path: tools/concourse/tasks/generate-version/task.sh

params:
  GIT_EMAIL:
  GIT_NAME:
