version: "2"
services:
  concourse-db:
    image: localhost:5000/postgres:9.6
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: concourse
      POSTGRES_PASSWORD: changeme
      PGDATA: /database
  concourse-web:
    image: localhost:5000/concourse/concourse:3.8.0
    links:
      - concourse-db
      - artifactory
    command: web
    ports: ["8080:8080"]
    volumes: ["./keys/web:/concourse-keys"]
    environment:
      CONCOURSE_BASIC_AUTH_USERNAME: concourse
      CONCOURSE_BASIC_AUTH_PASSWORD: changeme
      CONCOURSE_EXTERNAL_URL: "${CONCOURSE_EXTERNAL_URL}"
      CONCOURSE_POSTGRES_DATA_SOURCE: |-
        postgres://concourse:changeme@concourse-db:5432/concourse?sslmode=disable
  concourse-worker:
    image: localhost:5000/concourse/concourse:3.8.0
    privileged: true
    links:
      - concourse-web
      - artifactory
    command: worker
    volumes: ["./keys/worker:/concourse-keys"]
    environment:
      CONCOURSE_TSA_HOST: concourse-web
  artifactory:
    image: localhost:5000/docker.bintray.io/jfrog/artifactory-oss:5.5.1
    volumes: ["./artifactory.config.import.yml:/var/opt/jfrog/artifactory/etc/artifactory.config.import.yml"]
#    build:
#      context: .
#      dockerfile: Dockerfile-artifactory
    ports:
      - "8081:8081"
